name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install pip requirements
        run: pip install uv && uv pip install . --system

      - name: Check import
        run: python -c "from python_uv_template.hello import main"

      - name: Run tests
        run: pytest -v --cov --durations=0
